### ISSUE TITLE
Set up deployment to convert.glossarist.org

### ISSUE THREAD

**Issue by strogonoff** [glossarist/convert-glossarist.github.io#1]
Could someone help provision the subdomain and provide [relevant secrets](https://github.com/glossarist/migration-adapters/blob/a212d1297b9b0664480c7c24c5537879566eca3b/.github/workflows/deploy-convert.yml#L42-L60) in GitHub repository settings?

```
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
```

**Comment by ronaldtse** [comment]
Can we host this on GitHub pages? Then we don't need AWS

**Comment by ronaldtse** [comment]
Is this a Docker container? If so then it needs to be setup as Lambda, with no S3.

**Comment by strogonoff** [comment]
@ronaldtse it’s not a Docker container, it’s a fully static page.

**Comment by strogonoff** [comment]
As such I think it can be served from GHP, I don’t have a strong preference.

**Comment by strogonoff** [comment]
@kwkwan the repository is not being auto-deployed (latest commit is [last week](https://github.com/glossarist/migration-adapters/commit/31c8b5bd7f5bb1c97d0a1ad66b55ae2df783d2be) but deployment is [last month](https://github.com/glossarist/migration-adapters/actions/runs/6627125495), what’s the best way to avoid this for the next couple of months?

**Comment by ronaldtse** [comment]
@kwkwan could you please help deploy this? Thanks.
